### ISSUE TITLE
Remove all Ambiata libraries

### ISSUE THREAD

**Issue by thumphries** [thumphries/projector#2]
- [x] p
- [x] disorder-core
- [x] disorder-either
- [x] disorder-jack
- [x] machinator
- [x] umami
- [x] x-either
- [x] x-templatehaskell

**Comment by markhibberd** [comment]
About half of disorder is done here - https://github.com/thumphries/projector/compare/master...markhibberd:topic/hedgehog-again?expand=1 - will finish off on wednesday. As pointed out, the naive translation is a bit slow/hangy on larger sizes. The main difference is `Gen.recursively Gen.choice` vs `Jack.oneOfRec` which I think is biasing more heavily towards non-recursive case, will get it all translated and then do some tuning.

**Comment by markhibberd** [comment]
This is done. I was pretty brutal about just getting everything through, so there are lots of tidy-ups and improvements that could still be made, i.e. using hedgehog combinators better rather than a direct translation, renaming things around machinator. But at least it is independent now.
